### PR TITLE
TDE: Use and throw

### PR DESCRIPTION
**Pull request by JustAnotherNerdWhoLikesStuff**
Added the ability to use or throw an item.

### CODE REVIEW

**Comment by JustAnotherNerdWhoLikesStuff** [comment]
This is not finished yet, just mostly there.

**Comment by charlesamacon** [comment]
image
This is so much fun

**Review by charlesamacon — APPROVED** [review]

**Comment by JustAnotherNerdWhoLikesStuff** [comment]
AllBombDemoSmall

**Comment by charlesamacon** [comment]
image
The flashing red lights on the bomb bug out near the gravity bomb

**Comment by charlesamacon** [comment]
image
Better example

**Comment by JustAnotherNerdWhoLikesStuff** [comment]
Yeah, I observed the lighting bug when I was working on that effect, but I couldn't for the life of me figure out what was causing it.  It happens in regular intervals around the map and seems to be independent of level geometry.
Examples:
LightingBug1
LightingBug2
LightingBug3
LightingBug4
LightingBug5

**Comment by JustAnotherNerdWhoLikesStuff** [comment]
Also, I need to turn all of the bombs into prefabs.

**Pull request merged**
